### ISSUE TITLE
False illegal flags

### ISSUE THREAD

**Issue by SerraraFluttershy** [drgoku282/PKMN-NTR#100]
![fuck](https://user-images.githubusercontent.com/23690950/28040622-fdd7f92e-658b-11e7-91a8-db18305b1b0c.PNG)

This happened on a legitimate shiny Darkrai, caught in Platinum; it is legal in PKHex but not PKMN-NTR.

**Comment by drgoku282** [comment]
This happens because the last stable version of PKMN-NTR was build with an old version of PKHeX, updated the core in latest beta. It should be fine now.
