### ISSUE TITLE
Wonder Trade Bot Refuses To Trade Anything

### ISSUE THREAD

**Issue by WonderSquid** [drgoku282/PKMN-NTR#102]
It runs fine as far as actually getting into Wonder Trade with no connection issues and selecting a Pokemon. Then it deselects that Pokemon. Then it selects it again. Then it deselects it. Then it selects it again. Then it deselects it...

 It will continue to do this until it crashes after about fifteen minutes. I've checked if it was a legality issue using a random Exeggcute I caught and it won't trade that either. I've used both 3.4 and the 3.5 beta with no difference, and have experimented with all permutations of the settings (collect FC afterwards, don't, load Pokemon from box, load Pokemon from folder, run endlessly, don't), and it makes no difference. 

For some baffling reason, it WILL trade Pokemon that have been received from Wonder Trade ten minutes ago or less. Pokemon from previous Wonder Trade sessions will not be traded.

**Comment by drgoku282** [comment]
Can't reproduce, bot seems to be working fine for me. Will upload new version soon.

**Comment by AyanamiRei1** [comment]
I do apologise about this but I'm having the exact same problem with Sun 1.2 with Luma 9.1 it deselects the Pokemon. Then it selects it again. Then it deselects it. Then it selects it again. Then it deselects it.
