### ISSUE TITLE
Old 3ds not working

### ISSUE THREAD

**Issue by TomG-Official** [drgoku282/PKMN-NTR#104]
Works fine on new 3ds but not on my old 3ds witch is the one i want to do it on...

**Comment by TomG-Official** [comment]
when i start ntr and inputredirection  it works on new 3ds and i can access ntr on new 3ds 
but on the new-3ds it doesn't connect and i cant assess ntr menu

**Comment by drgoku282** [comment]
Are you sure you're using Mode3 NTR?

**Comment by GaaraOmega** [comment]
Same issue with me on O3DS.

However BootNTR, BootNTR Mode3, and NTR Selector 3 + InputRedirection does not connect to PKMN-NTR or anything else.

**Comment by GaaraOmega** [comment]
Do things in this order:
>start InputRedirector on your 3DS
>start NTR Mode3
>start desired game
>enable NTR debugger
>go to whatever part the game uses to connect you to the internet
>start PC client (make sure the config has your correct 3DS address)

**Comment by drgoku282** [comment]
Move discussion to #114 .
