### ISSUE TITLE
Can't connect to internet on ORAS while running NTR

### ISSUE THREAD

**Issue by JakeK0202** [drgoku282/PKMN-NTR#108]
I'm having an issue I never had before, I receive an error when I try to connect to the internet in ORAS while I'm running NTR, so I can't get online to even connect to PKMN-NTR. I'm on the latest release of luma (8.1.1 iirc) and NTR 3.6, debugger always says it's already enabled. I'm using the input redirection cia as well, so I'm not sure what the issue would be.

**Comment by Bappsack1994** [comment]
Remove your NTR Cheat Plugin
