### ISSUE TITLE
It Might Be Working?

### ISSUE THREAD

**Issue by OfficialBrony** [drgoku282/PKMN-NTR#109]
Okay, so I have downloaded this because I just want to Wonder Trade whilst I am AFK (well, in this case, AF3DS).
I have a New 3DS XL with Luma CFW B9S
My issue is that I know the Pokemon NTR .exe file is connected since it reads the correct Pokemon from box 1 slot 1, then I tested it with box 2 slot 1, all correct, so I know it is connected. 
I tried using Input Redirection through the Rosalina Menu and the .CIA file. 
This is a step by step list on what I do exactly
1. I load up the latest NTR CFW
2. I press X and Y to enable debugger (just in case)
3. I use my combo buttons to open Rosalina and start Input Redirection (or try again with the .cia)
4. I go on Pokemon Sun, spamming A while it is loading
5. I go to Festival Plaza and get online
6. I open up PKMN NTR.exe and type in my N3DSXL IP address. 
7. It is connected to PKMN NTR.exe, as I am able to read in Box 1, Slot 1
So you're wondering what my issue is, right? 
Well, my issue is when I go to the Tools tab, click on WT BOT and then I select Box 1 Slot 1 for 20 trades.
The WT BOT window shows it is doing something, then says Bot Finished Successfully when nothing happened on my N3DS. I know I shouldn't be doing anything wrong, as I do the similar steps for Ledybot and works 98% of the time for me when I play ORAS or XY.
Thanks for taking the time to read, and possibly help me guys or dev!
I should also mention that Pokemon Sun is a digital copy, ripped straight from my cartridge before I sold it. So it is a legit copy.
EDIT: No matter what box, trade number or slot number, the issue still remains for me.

**Comment by wrathsoffire76** [comment]
Try using InputRedirectionNTR

**Comment by drgoku282** [comment]
This program doesn't support Rosalina input redirection, use wiki for instructions.

**Comment by OfficialBrony** [comment]
Don't just close this and not tell me a way to make it work. 
Even the input redirect cia or the one built in NTR doesn't make the bit work. 
This project is a fail.

**Comment by OfficialBrony** [comment]
Going to re open this as a new issue
