### ISSUE TITLE
Commands -party and -hax not working

### ISSUE THREAD

**Issue by SAOGives** [drgoku282/PKMN-NTR#112]
Putting -party or -hax  in a command window does not work with PKMN-NTR.

**Comment by drgoku282** [comment]
The -hax argument seems to be working fine for me. Can you write steps to reproduce the issue, also try with latest version.

**Comment by SAOGives** [comment]
In the command window I placed the name of the folder (PKMN-NTR), put PKMN-NTR in the command window and placed -hax after it     Ex:( PKMN-NTR -hax)

**Comment by drgoku282** [comment]
Still not working? Can you please paste the exact command you write in the command line?

**Comment by SAOGives** [comment]
Works now, thanks.
