### ISSUE TITLE
It might be working? 

### ISSUE THREAD

**Issue by OfficialBrony** [drgoku282/PKMN-NTR#115]
Okay, so I have downloaded this because I just want to Wonder Trade whilst I am AFK (well, in this case, AF3DS).
I have a New 3DS XL with Luma CFW B9S
My issue is that I know the Pokemon NTR .exe file is connected since it reads the correct Pokemon from box 1 slot 1, then I tested it with box 2 slot 1, all correct, so I know it is connected.
I tried using Input Redirection through the Rosalina Menu and the .CIA file.
This is a step by step list on what I do exactly

I load up the latest NTR CFW
I press X and Y to enable debugger (just in case)
I use my combo buttons to open Rosalina and start Input Redirection (or try again with the .cia)
I go on Pokemon Sun, spamming A while it is loading
I go to Festival Plaza and get online
I open up PKMN NTR.exe and type in my N3DSXL IP address.
It is connected to PKMN NTR.exe, as I am able to read in Box 1, Slot 1
So you're wondering what my issue is, right?
Well, my issue is when I go to the Tools tab, click on WT BOT and then I select Box 1 Slot 1 for 20 trades.
The WT BOT window shows it is doing something, then says Bot Finished Successfully when nothing happened on my N3DS. I know I shouldn't be doing anything wrong, as I do the similar steps for Ledybot and works 98% of the time for me when I play ORAS or XY.
Thanks for taking the time to read, and possibly help me guys or dev!
I should also mention that Pokemon Sun is a digital copy, ripped straight from my cartridge before I sold it. So it is a legit copy.
EDIT: No matter what box, trade number or slot number, the issue still remains for me.

**Comment by drgoku282** [comment]
Try it without activating Rosalina. Also try latest release. Bots are working fine for me.

**Comment by drgoku282** [comment]
Any updates? Have you tried another bots? Do you have any log file?

**Comment by drgoku282** [comment]
Closing this due lack of feedback.
