### ISSUE TITLE
No NFC Patch for USUM

### ISSUE THREAD

**Issue by Real96** [drgoku282/PKMN-NTR#119]
[No NFC v1.0]
203F1F00 00000000

[(Start + L/R)Disable/Renable inGame NFC]
D3000000 00000000
DD000000 00000208
203F1F00 00000000
D0000000 00000000
DD000000 00000108
203F1F00 00000001
D0000000 00000000

Useful for deny the game to disconnect the console from internet ;)

**Comment by drgoku282** [comment]
Thanks, but I actually can't read that, can you please tell me on how to convert that code on a memory address?

For example: For disabling NFC on SM I need to write the value 0xE3A01000 in RAM direction 0x3E14C0.

Please move discussion to #120 .
