### ISSUE TITLE
PKMN-NTR Problems With Mystery Gift DataBase

### ISSUE THREAD

**Issue by Blizzard929** [drgoku282/PKMN-NTR#121]
Im Using PKHex and PKMN-NTR because PKHex has this big Pokemon Database function with a bunch of filters. U can Filter by Illegal and Legal Pokemon and thats very good. The Main Readson for my Problem today is that PKMN-NTR doesnt accept MOST of the Legal Pokemon from the Mystery Gift Database.
1. Stop Blocking Users to Write Illegal Pokemon to their save Files.
2. Pls Change the Function of ure PKMN-NTR Illegal Checker (Mystery Gift Database).
I just wanna send Pokemon to my Game in a easy and quick way i cant do with other Tools, the main problem is that i cant write the most Pokemon to the game because PKMN-NTr blocks it mostly of the reason of a mystery gift database error.
Sorry for my bad English but i hope u know what i mean.
For the idea to not block user from sending illegal pokemon to their game, just add acheckbox with "illegal write blocker" or something like that with a big warning that illegal pokemon can be the reason for a ban.
Im jsut wondering because so many Pokemon that are Legal by PKHex are illegal for PKMN-NTR so pls fix that.

**Comment by drgoku282** [comment]
If you're using the last stable version, it was built with an old version of PKHeX, so it might miss a few of the recent checks, but you can always inject illegal pokemon if you start the program with the -hax command.
