### ISSUE TITLE
Can you pls remove the pop-ups on illegal mode when trying to inject an illegal Pokemon

### ISSUE THREAD

**Issue by Naturally-Delicious** [drgoku282/PKMN-NTR#123]
It's really annoying, especially if the Pokemon you're injecting is 100% legitmate, but it's just marked as illegal by pkhex. maybe have an option to turn them off? (so ppl who like the pop-ups can still have them)

**Comment by Bappsack1994** [comment]
enable .HaX Mode

**Comment by Naturally-Delicious** [comment]
I do have HaX mode on. It still shows a pop-up whenever I try to inject an "illegal" Pokemon.

**Comment by Bappsack1994** [comment]
then edit the source and compile it.

**Comment by Naturally-Delicious** [comment]
sorry man but i don't know how to program. don't even know what "compile" means.

**Comment by drgoku282** [comment]
Will consider removing nags, low priority for now until USUM support is complete.

**Comment by drgoku282** [comment]
I hope I fixed this thing on 3fdef17, when the new version is up, feel free to test it and tell me if it works.
