### ISSUE TITLE
Checking "Suppress HaX warning messages" error

### ISSUE THREAD

**Issue by Naturally-Delicious** [drgoku282/PKMN-NTR#127]
Checking `Suppress HaX warning messages` in `about` tab doesn't suppress any HaX message, but instead prevents you from writing the illegal Pokemon at all, and shows this message:

`"The Pokemon is illegal, it won't be writted to the file" PS. `
PS:"written" is the correct term. (Sorry to be grammar nazi...)

Which I believe is the message you would get in the normal mode... and yes, I am using the HaX version of PKMN-NTR.

Pls fix when you have time! Thank

**Comment by drgoku282** [comment]
Will look on this, but it will take a least a few weeks, I will be far from my computer due holidays, I will mark as a duplicate of #123 .
