### ISSUE TITLE
Some pokemon that are valid in PKHeX aren't valid in PKMN-NTR

### ISSUE THREAD

**Issue by EragonShade98** [drgoku282/PKMN-NTR#128]
I attempted to gen in a legal marshadow, but PKMN-NTR refuses to let me do so without using the -hax tag. I think this may be a bug because when I get the legal file from PKHeX's event/mystery gift database, PKMN-NTR still thinks the pokemon is illegal.

Here is a link to an image comparing the original file from PKHeX to the exact same file, but in PKMN-NTR:
https://cdn.discordapp.com/attachments/366401377796227075/393181743525396490/20171220_182323.jpg

**Comment by FrozenDragoon** [comment]
The version of PKHex in PKMN-NTR has not been updated in a while. 
https://github.com/drgoku282/PKMN-NTR/blob/2d2b9f742f9432b3e9db9d3f11d4f7af29ce7b65/PKMN-NTR/MainForm.cs#L176

The version of PKHex you are using on the right is 20171205.

See #120 (not specifically related to PKHex-Core, but drgoku mentioned how he has limited time these days)

Out of curiosity, what is PKMN-NTR complaining about, legality-wise?

**Comment by EragonShade98** [comment]
@FrozenDragoon It's complaining about not being able to pull the pokemon from the mystery gift database. Is there any way  to force it to use the updated version?

**Comment by drgoku282** [comment]
Currently there's no way to update the internal PKHeX.Core and currently there are no plans to change this, mostly because updating the core can break other things in the program and cause unexpected behavior.

The only workaround is using the hax mode.

**Comment by drgoku282** [comment]
Also try with latest alpha version, it was built with the last stable version of PKHeX.
