### ISSUE TITLE
Dragging a shiny Pokemon from PKHeX to PKMN-NTR changes it to non-shiny.

### ISSUE THREAD

**Issue by Naturally-Delicious** [drgoku282/PKMN-NTR#129]
Please fix when you have time!! Your work is very appreciated :)

**Comment by drgoku282** [comment]
It seems a possible duplicate of #126 does exporting the pokemon as a .pkx file from PKHeX and importing it again on PKMN ntr work correctly?

**Comment by Naturally-Delicious** [comment]
Yes.

**Comment by drgoku282** [comment]
Will mark this as a duplicate of #126 and close this issue. Anything related to this bug will be discussed there.
