### ISSUE TITLE
WT Bot Isnt working for me

### ISSUE THREAD

**Issue by pkmnlovr74** [drgoku282/PKMN-NTR#131]
I am currently running version 3.5 on pokemon sun version. I followed the instructions. I connected, set up the bot, connected to internet, hit run and nothing happens. I copied some of the log. any help would be much appreciated

Bot: Press Trade Button
NTR: Touch the screen at 200,120
NTR: Touch screen command sent correctly
Bot: Test if the trademenu is shown
NTR: Read data at address 0x006749DC during 5000 ms
NTR: Expected value 0xC2D00000 to 0xC2DFFFFF
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0xC2C00000
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0xC2C00000
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0xC2C00000
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0xC2C00000
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0xC2C00000
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0xC2C00000
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0xC2C00000
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0xC2C00000
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0xC2C00000
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0xC2C00000
NTR: Command timed out
NTR: Value in range: No
NTR: Read failed or outside of range

**Comment by Mitsukiii** [comment]
Did u actually have the NTR Input Redirection running? did the Bot click on the Trade Button? it seems not, because the Offset '0x006749DC' returns '0xC2C00000' and thats the Value for outside of the Trademenu, that means actually you re not IN the Trade Menu.

**Comment by pkmnlovr74** [comment]
I think I am, I'm using NTR Amode 3 on an o3ds. I enable the debugger. I didn't know you have to be in the trade menu. I also tried the other functions like breeding and remote control, and they don't work either. The only thing that works for me is the genning reader/writer

**Comment by Mitsukiii** [comment]
Yup, u forgot the Input Redirection.

https://github.com/Stary2001/InputRedirection/releases

Run BootNTR And InputRedirection before starting the Game.

**Comment by pkmnlovr74** [comment]
It worked. Thank you so much. I really appreciate it. Happy new year
