### ISSUE TITLE
How can i change the normal mode into illegal Mode?

### ISSUE THREAD

**Issue by Shinyhunter2109** [drgoku282/PKMN-NTR#133]
Hello i hope someone can help me. I use atm the normal mode for PKMN-NTR but i want to wondertrade mythicals but i dont know how. I know i have to change it into hax mode but i dont know how to open the Programm from a Command window ?

Thanks in Advance

**Comment by Mitsukiii** [comment]
use the Command Line -Hax Parameter.

For example:

Open CMD and launch PKMN-NTR:
C:/Users/Username/Desktop/PKMN-NTR.exe -HAX

**Comment by Shinyhunter2109** [comment]
OK Thank you 👍
