### ISSUE TITLE
Question: Can I use this tool to work with OBS?

### ISSUE THREAD

**Issue by The-f6X** [drgoku282/PKMN-NTR#139]
I'm working on [this project](https://github.com/The-f6X/Gen4OverlayScript) which takes in text file inputs from DeSmuMe and configures  some text files and images to go with what my current team's state is for my twitch stream. 

Currently, the project I'm working on dumps text files from DeSmuME with the current team information which get read by a python script to generate team images and status files. I want to export current team information to a text file using PKMN-NTR, is there any way that this can be done? 

Thanks.

**Comment by drgoku282** [comment]
PKMN-NTR can dump party slots, then handle the information to PKHeX.Core to get pokémon data from RAM and then use that to output a text file, maybe a bit similar to the .csv data report from PKHeX.
