### ISSUE TITLE
Egg Hatcher

### ISSUE THREAD

**Issue by drgoku282** [drgoku282/PKMN-NTR#14]
Make a bot that can hatch eggs from the PC.

**Comment by ChaosTherum** [comment]
Would it also be possible to implement another option along with the breeding bot that could make the pokemon hatch after a couple steps while breeding similar to the current fast breeding option.

**Comment by drgoku282** [comment]
After some time I think this feature is not needed, then this will not be implemented. Any hatching would be faster by just modifying the friendship of the egg.
