### ISSUE TITLE
PKMN-NTR disconects starting the game on 1.2

### ISSUE THREAD

**Issue by Guadalupe64** [drgoku282/PKMN-NTR#145]
I have just tried the PKMN-NTR in US 1.2, it conected in the tittle screen but when I started the game it disconects, I'm on a new 3DS.

**Comment by CosasDePuma** [comment]
This is because Pokemon games disconnect Wifi if they are not using Online functions.

Try next:

- Go to Festival Plaza and connect gme throught Internet and then connect the PKMN-NTR
- Enable debug mode in Rosalina before open USun.
