### ISSUE TITLE
USUM 1.2 compatibility

### ISSUE THREAD

**Issue by drgoku282** [drgoku282/PKMN-NTR#148]
Creating this issue to avoid duplicates.

**Comment by Mitsukiii** [comment]
NFC Offsets:
0x3F3424// Ultra Sun  
0x3F3428// Ultra Moon
--
Trademenu Offset
trademenuOff = 0x006A62E6; // TradeMenu Button Offset
trademenuIN = 0xC2D0; // In Trademenu (Link Trade, GTS, Wondertrade)
trademenuOUT = 0x3E98; // Outside TradeMenu (Battle, Trade)
SearchPartner = 0x42AC;
DuringTrade = 0x3F80;
tradeEvo = 0xBF80; // Trade Evolution

WTButton Offset:

WTButtonOFF = 0x006A62B2; // Wondertrade Button Offset
WTButtonIN = 0x00; //Wondertrade Button Shown
WTButtonOut = 0x3F800000; // Fishy mostly 0x3F80, sometimes 0x3F40

BoxScreen Offset:

BoxScreenOff = 0x006A6132; // Box Menu
BoxScreenIN = 0x4221; // Box Menu Visible
BoxScreenOut = 0x4222; // Not in Box Menu

This work all with US and UM.

**Comment by drgoku282** [comment]
Thanks for the offsets, I just finished the PKHeX core update and was about to start doing RAM research. I'll test them and if everything is ok I'll start to work on the breeding bot.

**Comment by Mitsukiii** [comment]
the Instant Egg Offset wasnt changed, didnt tested the Screen Offset.

**Comment by drgoku282** [comment]
From my experience, everything in memory region 0x30000000 - 0x34183fff doesn't change between updates (this region has all data which can be accesed via PKHeX).

Screen offsets are in region 0x00100000 - 0x006d3fff, and these always change every update, breaking the program.

Tested WT bot with your offsets and it seems to be working fine. Currently searching for a dialog offset for the breeding bot, I already have the memory dumps so I might push update soon (tm).

**Comment by Mitsukiii** [comment]
this Offset are my private Offsets, they didnt changed from 1.0 - 1.2, thats weird. But you re right, 0x00100000 - 0x006d3fff changes sometimes after a Update, but mostly they moved only one or two bytes +.

**Comment by codster88** [comment]
I’m having an issue with Ultra Moon Bot it trades fine then sadly it stops working cause Ram couldn’t be read or Something else happens is there a fix for this?
