### ISSUE TITLE
ORAS Battle Resort Daycare breeding bot error

### ISSUE THREAD

**Issue by JakeK0202** [drgoku282/PKMN-NTR#149]
Any time I run the breeding bot in ORAS the bot is able to collect the first five eggs, deposit them, then walk out of the daycare and walk straight past the daycare boy into a wall and continues walk to the right into the wall until an error message comes up after a few minutes. This is on the battle resort, haven't yet tested route 117. Soft reset bot also will not run at all. I'm just getting an error reading 3ds ram. I can't get either bot to run correctly or at all.

**Comment by drgoku282** [comment]
Can't reproduce, bots are working fine for me. Make sure you have a strong connection on your 3DS, also, do you have any log?

**Comment by JakeK0202** [comment]
Good/Bad news, I set up the breeding bot to run this morning to produce a log file for the error, and I couldn't reproduce it. I'm going to let it run for a while to see if it will happen at all. I'll try to get a log for the SR bot when I can though. Also, thanks for such a quick response. Nice to know you're on top of your project.

**Comment by JakeK0202** [comment]
Never mind, I spoke too soon. I broke the breeding bot again, here's the log.
[20180304123324_pkmn-ntr.txt](https://github.com/drgoku282/PKMN-NTR/files/1778758/20180304123324_pkmn-ntr.txt)

**Comment by drgoku282** [comment]
I can't figure what's wrong, your systems seems to ignore commands sent by the bot for some reason, is the trainer getting stuck in some place?

**Comment by drgoku282** [comment]
After checking, I think fix position commands are in the opposite direction, wait for update, what about the SR bot.

**Comment by JakeK0202** [comment]
I'm setting up SR bot right now. I'll send a log with starting and one for resuming the bot because I get different results

**Comment by JakeK0202** [comment]
Still getting errors for the SR bot too, here's the logs for starting it normal and trying to resume it.
[StartBot_pkmn-ntr.txt](https://github.com/drgoku282/PKMN-NTR/files/1778791/StartBot_pkmn-ntr.txt)
[ResumeBot_pkmn-ntr.txt](https://github.com/drgoku282/PKMN-NTR/files/1778792/ResumeBot_pkmn-ntr.txt)

**Comment by drgoku282** [comment]
Are you sure you're starting the bot on the correct window (see wiki)  because it is not reading the expected value, and about the resume, is your 3DS soft reseting correctly, the bot seems to fail when it tries to reconnect to the 3DS.

**Comment by JakeK0202** [comment]
It soft resets and the bot gets it back into the game. It'll choose the save file and after that it can't reconnect so I assume it's soft resetting correctly. And as far as starting, it's from the screen with pss settings on it, right?

**Comment by drgoku282** [comment]
Yes the soft reset is doing fine, but for some reason the program or your 3DS can't reconnect. And for the second thing, yes, you must start from that window.

Can somebody else tests those bots to check if they're working correctly?

**Comment by drgoku282** [comment]
Will use this issue for the ORAS breeding bot error, feel free to open another issue for the SR bot error.
