### ISSUE TITLE
Ultra Moon Wonder Trade Bot breaks on new Dex entry

### ISSUE THREAD

**Issue by k20stitch** [drgoku282/PKMN-NTR#158]
Let me know what the command to read the correct offset and let me know where in the source code to put it and write it to the console.

**Comment by Bappsack** [comment]
theres no Detection for a new Dex Entry, read the Wiki and fill your Pokedex with PKHeX.

**Comment by k20stitch** [comment]
Where in the wiki does it say this? It states the only untested issue is evolution.  It’s also not listed as a known issue or anywhere in the wiki that I can see. But thanks anyways.

**Comment by k20stitch** [comment]
Now all of a sudden new dex entries work? If i build in Debug mode will it collect anything useful in finding out the correct offsets?

**Comment by Bappsack** [comment]
No, i dont really remember, but 0x6A62E6 returns a 0x0 if a new dex entry is present, but its still easier to complete the dex with PKHeX.
