### ISSUE TITLE
Window layout when running under Mono (Linux)

### ISSUE THREAD

**Issue by shadowofdarkness** [drgoku282/PKMN-NTR#25]
The connection section is shifted up when running PKMN-NTR in Mono on Linux. Other then that it works great.

To get around not being able to see the boxes I was able to get this running by doing 5 alt-tab combos (on beta, needs 6 for last release) on the keyboard then blindly inputting the IP then after 5 tab presses to get back to the connect button just hit enter to connect.

After the first use since it saves the IP luckily I just open the program and hit enter first to connect then everything works great.

Under Wine the layout is fine but the bot fails to run. So I assume it would be easier for you to fix the layout in mono then fix the problems in Wine.

Tested both the last release and the beta with breeding.

**Comment by drgoku282** [comment]
Does the bots fail completely?

A question, does Mono/Wine fully support .NET Framework 4.5. Because the bots depend on asynchronous programming (async/await) which were new in this version:

https://msdn.microsoft.com/en-us/library/mt674882.aspx

**Comment by shadowofdarkness** [comment]
The bot does work with Mono it is just visual problems
With Wine no visual problems but the bot fails

I have attached screen shots showing the error in Wine when I hit the run bot button
Also a screen shot of mono where everything works but with visual problems (I have tried the SR bot for a good 7 hours without problems)

Really the wine problem shouldn't matter since people can just use Mono which runs fine.

![mono](https://cloud.githubusercontent.com/assets/1281073/19827142/e79f82c8-9d5c-11e6-85e6-98c1b3228a9e.png)
![wine](https://cloud.githubusercontent.com/assets/1281073/19827141/e79ecee6-9d5c-11e6-986e-facc602afa0d.png)

**Comment by drgoku282** [comment]
Gui changes added on latest commit, will be out on ver 1.19.2.

**Comment by shadowofdarkness** [comment]
Thanks, I just tested it and the connection area is now visible along with the opponent check box in the dump and edit section.

The only ones that didn't change are in the breeding tab the "Top" and "Battle Resort" options are still cut off like in the first screen shot.

**Comment by drgoku282** [comment]
GUI was modified in latest version, tell me what do you find.

**Comment by shadowofdarkness** [comment]
It looks pretty good just a couple broken borders. I went through all tabs and these are the only broken borders.

![screenshot from 2016-11-10 18-21-01](https://cloud.githubusercontent.com/assets/1281073/20201110/df560f7c-a772-11e6-8b38-c51ae8a08a4c.png)

**Comment by drgoku282** [comment]
It seems the broken borders are caused by the length of the labels. They are not fixable but also doesn't have any impact on the application. So I'll consider this issue closed.
