### ISSUE TITLE
Add filter for wondertrade [Enhancement]

### ISSUE THREAD

**Issue by ChaosTherum** [drgoku282/PKMN-NTR#30]
I was wondering if you could add filters to wondertrade as well. Particularly one that checks to see if the pokemon is in your pokedex yet or not and then retrades it if not.

**Comment by drgoku282** [comment]
I don't have ram address to implement such feature, and pokédex editing also isn't a planned feature.

**Comment by ChaosTherum** [comment]
Okay well would it be possible to filter for a particular pokemon then this could also allow a similar function.

**Comment by drgoku282** [comment]
Is possible, it will be put on low priority until gen 7 support is implemented.

**Comment by ChaosTherum** [comment]
Okay thanks for the consideration.

**Comment by drgoku282** [comment]
After considering it, I think a wonder trade filter seems pointless, the probability of getting a specified pokémon is very low so no such feature will be implemented.
