### ISSUE TITLE
TwitchChat bot for WTbot

### ISSUE THREAD

**Issue by AlejaKaiser** [drgoku282/PKMN-NTR#31]
Hi. I want to use in my Twitch Stream the WonderTradeBot, but there it's a delay. Could you add a tool to do a countdown via chat? Like this streamer do

https://www.twitch.tv/auslove

**Comment by drgoku282** [comment]
I have no idea how does Twitch Stream work or if if they have an API to check comments from an external application. Anyways you mention there's a delay, but it's probably part of the bot and cannot be changed. 

Regardless of this, I do not plan to implement such feature. Also remember that if you want to stream you need a capture card as PKMN-NTR can't work at the same time as NTR-Viewer.
