### ISSUE TITLE
Enhancement: Enable Gen7 Connection w/o Festival Plaza

### ISSUE THREAD

**Issue by AnalogMan151** [drgoku282/PKMN-NTR#32]
Run NTR, run game, suspend game with HOME button, connect with PKMN-NTR, run following command to disable inGame NFC:

write(0x3DFFD0, (0x00, 0x10, 0xA0, 0xE3), pid=0x??)

Resume game and link will remain established.

**Comment by drgoku282** [comment]
Will check on this.

**Comment by roflpwnt** [comment]
What PID am I applying this to?

**Comment by drgoku282** [comment]
I don't understand your question,

**Comment by roflpwnt** [comment]
He says to run the command 

`write(0x3DFFD0, (0x00, 0x10, 0xA0, 0xE3), pid=0x??)`

Shouldn't there be a PID value instead of "??"

**Comment by drgoku282** [comment]
Yes, you need the PID of the Sun/Moon process, to find it you need the process list and find the PID of the process named "niji_loc", this is the SM PID.

**Comment by roflpwnt** [comment]
Thank you for the clarification.
