### ISSUE TITLE
Can't dump Pokemon

### ISSUE THREAD

**Issue by mew351** [drgoku282/PKMN-NTR#35]
When clicking dump I get
rtCheckRemoteMemoryRegionSafeForWrite failed: d8e007f5

**Comment by drgoku282** [comment]
More information? Game, pokemon source (boxes, party, battle box, etc.?

**Comment by drgoku282** [comment]
http://gbatemp.net/threads/pkmn-ntr-real-time-memory-editing-program-for-pok%C3%A9mon-games-wip.448588/page-5#post-6891918

This build should have fixed the issue.

**Comment by YoshiOG1** [comment]
Hey, whenever I try to dump a Pokemon that's in a Beast Ball, it gives me an error and doesn't finish dumping the Pokemon:

InvalidArgument=Value of '25' is not valid for 'SelectedIndex'.  Parameter name: SelectedIndex

It still persists in 2.0.0-beta5 :(
