### ISSUE TITLE
Breeding Bot (Gen 7) high box numbers

### ISSUE THREAD

**Issue by owensar** [drgoku282/PKMN-NTR#36]
Breeding bot after box 26 doesn't switch box successfully. 

Restarted both 3DS and App.

Boot NTR - InputReDirect - Debugger - Game

Open App - Connect

Try to deposit eggs via bot to overflow box:

Bot opens box and sees that it is full, tries to switch box. It reopens the same box, and tries to overwrite slot 1. Bot eventually crashes.

**Comment by drgoku282** [comment]
I can't reproduce the problem, transition from box 25 to 26 and from 26 to 27 is working fine for me. Can you provide more details? Like the mode you're using, amount of eggs deposited before, etc.

**Comment by danne2** [comment]
Literally just reproduced it and am submitting a pull request with a fix. Positions were wrong.

**Comment by danne2** [comment]
Pull request has been submitted #40

**Comment by drgoku282** [comment]
Will merge later today, thanks for the fix.

**Comment by danne2** [comment]
No problem. Glad to contribute. Might submit some other fixes/improvements here or there.
