### ISSUE TITLE
Delete Pokemon Question

### ISSUE THREAD

**Issue by imaboy321** [drgoku282/PKMN-NTR#37]
I was interested in what you were writing to the game to erase the pokemon and I noticed something. When you check if it is gen 7, you have it write an empty gen 6 file and when it isn't gen 7 you write the gen 7 one? MainForm.cs line 2065

**Comment by drgoku282** [comment]
Good eye on that detail, I didn't noticed it before. Will fix it later, don't worry, as long the species index is zero the game will treat the slot as empty and the two files are nearly identical.
