### ISSUE TITLE
Speedup Gen7 Breeding Bot

### ISSUE THREAD

**Issue by Stoned1337** [drgoku282/PKMN-NTR#43]
Hey Guy. The new Commit is Nice for the Breeding Bot.

Is There a Way to Speedup the Bot? For Faster Dialog Skipping?

**Comment by drgoku282** [comment]
Yes, I can make button presses faster but the trade-off is making the bot more likely to break, miss inputs or doing unwanted actions, like starting a dialog before an egg is generated, so I decided to sacrifice speed for reliability.
