### ISSUE TITLE
6 Gen Event softreset Bot bug

### ISSUE THREAD

**Issue by Real96** [drgoku282/PKMN-NTR#45]
After adding all the checks, sometimes there is a bug that still happens after 100-200 softreset. The log keeps saying "try to read party", but it didn't start the dialog with the lady yet. And so there is a loop of "try to read party" without any results. But if during this loop I start the dialog pressing A, it continue working as before, it checks the party and softresets without stopping. Can you add a check that after like 10-15 "try to read party" without any results, it sends the command to trigger the dialog pressing A button? In that way it will fix completely the bug i think

**Comment by drgoku282** [comment]
This problem is caused by lag in your end, as the soft-reset took too much time, the title screen/continue windows produces the same values in ram as starting the dialog that's the reason why the bot thought the dialog had started, will try to fix.
