### ISSUE TITLE
Gen 6 - Still stop while soft resetting + Strange crash

### ISSUE THREAD

**Issue by Liger0** [drgoku282/PKMN-NTR#47]
So, with the latest release the program now is more stable, but I still encountered some issues.
1. It still stops before talking to the lady (after a lot of resets, 456 in this case). [log](https://www.zerobin.net/?38723f1e0bf120ae#ZOLUYuGbkk9zRR7s9HvYSiGLEOvm/4plQqCaMT7ftzs=)

2. I encountered again the issue "An error occured while reading data from you 3ds ram, please check connection and try again". It happens, as before, before talking to the lady, but the strange thing is that also If I restart the bot, when I click connect it says IP is wrong, so maybe this problem is related to the NTR itself? [log](http://pastebin.com/wyp4cMtm)

3. The game stopped at the phrase: "I received a gift for you!", and nn the program it opened up a window saying "impossiblle to access deleted object. Name of the object: "System.net.Sockets.Networkstream".  [log](https://www.zerobin.net/?b6d3cd980c4223cd#kvfoF5LbAEHSam9hCWQB4i6o3Uscm1GbysqL8LvQgv4=)

**Comment by drgoku282** [comment]
Did you stop the bot in the first one or it stopped with a message error?

The other two were problems in your 3DS internet connection, can't do anything about them.

**Comment by Liger0** [comment]
I stopped the bot because I did wait a lot of time and nothing happened.

**Comment by drgoku282** [comment]
It seems two things happened with that, first, something weird happen with your RAM. The log shows that it passed the dialog start test so it tried to continue the dialog. And second, NTR and/or your 3DS started to ignore the commands sent by the application, it happens sometimes and the reconnections at the end of the log try to fix them but it seems they failed.

Next time this happens, try to press the A button manually, that usually makes the bot continue normally. If it doesn't then is either it's a connection error or a NTR error.
