### ISSUE TITLE
Add Button to generate Egg and a text box to whatch the actual egg seed

### ISSUE THREAD

**Issue by Real96** [drgoku282/PKMN-NTR#53]
Can you pls add a button that generate an egg after being pressed? And also, can you add a text box that shows the acual egg seed? I think it won't be so difficult

**Comment by drgoku282** [comment]
Egg seed dumping was added on a recent commit, will look on the egg button.

**Comment by drgoku282** [comment]
I don't think a button for producing an egg is needed, it would make more harm than benefit as people could create invalid eggs with it. I can check if there are parents in the daycare but no if they can produce an egg.
