### ISSUE TITLE
ability to dump from playing battle videos

### ISSUE THREAD

**Issue by realquantumsource** [drgoku282/PKMN-NTR#55]
with ntr command
data(0x32B9D5E4, 0x2BC0, filename='Video', pid=0x29)
you can grab pokemon data from the playing battle  video. can this be incorporated to show the data from the playing video in this program

**Comment by drgoku282** [comment]
Does this offset still work on ver. 1.1? If so I can add a command to dump the battle video entirely, reading pokemon from it will be considered at a later time.

**Comment by realquantumsource** [comment]
based on my testing yes it still does

**Comment by realquantumsource** [comment]
I should be able to help and give you the offsets for all the slots for pkm data

**Comment by drgoku282** [comment]
A lot of changes will be made to the program core (see #66), this feature will not be completed before I start making these changes. anything regarding this feature will be put on hold.

**Comment by drgoku282** [comment]
There is little interest on this feature, will not implement battle video dumping.
