### ISSUE TITLE
Wonder trade bot wanting to go to gts

### ISSUE THREAD

**Issue by TheSecretSword** [drgoku282/PKMN-NTR#57]
When i try to run the wondertrade bot it heads to the gts and gets just gets stuck

**Comment by TheSecretSword** [comment]
Here a video i ran it twice and the last time i showed the NTR Log if there is any info u need from that

https://www.youtube.com/watch?v=_xq64vXdDpM&feature=youtu.be

(it should be uploaded in about 5 mins after i post this

**Comment by YoshiOG1** [comment]
Good to know I'm not the only one having this issue since the 1.1 update.

**Comment by drgoku282** [comment]
Hope the new memory address will fix this problem.

**Comment by drgoku282** [comment]
Partially fixes #56

**Comment by TheSecretSword** [comment]
How fix issue? do i need to update?

**Comment by drgoku282** [comment]
You need to wait until I release a new version or compile the latest commit yourself.

**Comment by TheSecretSword** [comment]
if only i knew how to do that :P
