### ISSUE TITLE
GTS Mode

### ISSUE THREAD

**Issue by Loadie** [drgoku282/PKMN-NTR#61]
Hey Goku, love the work. I've been expanding and should probably commit soon. I added another bot mode where it uses the GTS to deposit the boxes, waits for someone to take it, then repeats the process. I've been trying diligently to write another bot mode where I use the GTS to seek a specific Pokemon, and give the person their desired Pokemon. I'm having trouble dumping the memory to find specific addresses and was wondering if you could point me in the right direction. I'm trying to determine the name Nickname of the Pokemon in the search screen (of GTS), as well as the actual species of the Pokemon being requested, then correlating it to a correct box/slot. I believe finding the Poke in the box won't be a problem once I can determine the requested species. Is there another medium we can speak on to work more closely on this? Are you even interested in this?

Also, I've integrated mIRC and YouTube API for timers that someone else had requested. The foundation anyways. Thanks in advance.

**Comment by Avalarion90** [comment]
i'd like to test your mirc support.

**Comment by drgoku282** [comment]
This program does something similar: https://github.com/olliz0r/Ledybot

From what I've seen on that code the strings are in the same section as most data, you can dump the entire region starting from 0x30000000 with a size of 0x42DC000, but probably you can narrow it to the region between 0x30500000 to 0x30800000.

About the mIRC feature, I don't know what is used for or anything but feel free to sumbitt a pull request when it's ready.

**Comment by Loadie** [comment]
Got it. Thanks Goku. That will help immensely. I will report back when I apply changes tonight.

On a side-note, the mIRC feature is for Twitch chats, they work off mIRC. I also added YouTube API for chats. I saw people requesting countdown features, so I added that in sometime last week.

**Comment by drgoku282** [comment]
No problem, but make sure to check the latest commit on the develop branch to make sure there are no conflicts,, as the Gen 7 wonder trade bot got some new features.

**Comment by Loadie** [comment]
There shouldn't be conflicts. I added a new tab for GTS functions and a new GTS class.

**Comment by imaboy321** [comment]
Hey there. Just want to note that Olli's ledybot was taken over by me. You can find the latest version here: https://github.com/imaboy321/Ledybot

**Comment by drgoku282** [comment]
A lot of changes will be made to the program core (see #66), this feature will not be completed before I start making these changes. anything regarding this feature will be put on hold.

**Comment by drgoku282** [comment]
This feature is covered by Ledybot, I will consider implementing my own verison in the future, but it isn't likely to happen.
