### ISSUE TITLE
[Feature Request] Gen 1 VC support

### ISSUE THREAD

**Issue by shadowofdarkness** [drgoku282/PKMN-NTR#64]
Would you be willing to add support for the old games. I would like the ability to see the opponent DVs before catching to hunt for potential shiny Pokemon when transferred to newer generations.

Using a SR bot on the legends would be great especially since this is the first source of them that can be shiny and HA at the same time.

It would be best for the shiny check to use both DV combinations the currently bugged g7 one that swaps attack and defense to get shiny immediately and the original g2 one which would just require waiting for them to fix it to transfer, which will have to be done before g2 VC to not break peoples shinies.

At least with both sets of combinations you nearly get double shiny odds 15/65536 instead of the regular 8/65536 and I like that I can choose a nature at transfer time by battling to adjust experience

**Comment by drgoku282** [comment]
Gen I games are very different from Gen VI/VII games so there's no easy way to port functions to VC games. Then such feature will not be implemented by me.

**Comment by shadowofdarkness** [comment]
I understand, I'll just do it the manual way then. At least I already found the wild encounters DV's in RAM with NTR so I can have my computer show them in a live view, then I'll just do the resets manually.
