### ISSUE TITLE
Bot has a fit when someone request a trade

### ISSUE THREAD

**Issue by TheSecretSword** [drgoku282/PKMN-NTR#68]
While sitting in festival plaza wonder trading someone will request to battle or trade and since u cant disable that as far as i know is there anyway the make the bot realize someone sent trade invite and wait for the trade to go away then resume trading? otherwise the bot basically bricks itself and i have to close and reopen it

**Comment by Loadie** [comment]
This isn't my project, however, I don't think anyone needs to write code to fix this problem. Secret Sword, in the festival plaza click the purple icon that has a person silhouette. It will open up a menu to disable the needed settings so you don't get interrupted. They are the last three options. You can disable all trade requests, etc.

**Comment by drgoku282** [comment]
Disabling communications with Guests is enough as a workaround to this problem. Will add the recommendation to the wiki.
