### ISSUE TITLE
1.2 patch for SuMo breaks many bots.

### ISSUE THREAD

**Issue by proflayton123** [drgoku282/PKMN-NTR#80]
Do you possibly have an eta when it will be supported for it? Thanks!~

**Comment by stratosfeargaming** [comment]
All bots down for 1.2??? and is there any Eta? can any1 answer please

**Comment by MichiS97** [comment]
They are all working again. Just download the latest release.

**Comment by drgoku282** [comment]
We haven't received reports of bots not working, so I just changed the beta to a stable release.
