### ISSUE TITLE
WT Bot isnt working for me

### ISSUE THREAD

**Issue by PumPum7** [drgoku282/PKMN-NTR#84]
When I start the WT Bot it just says :

> Please go to PSS Menu and try again

What should I do? 
This is the log:
 Test if the PSS menu is shown
rtCheckRemoteMemoryRegionSafeForWrite failed: d8e007f5

**Comment by drgoku282** [comment]
Can I have more info about this? Version, game you're using, steps to reproduce error etc.

**Comment by PumPum7** [comment]
Version: 3.3 so the newest
Game: SuMo 1.2
I just press on start then this happens:
Test if the PSS menu is shown
rtCheckRemoteMemoryRegionSafeForWrite failed: d8e007f5

**Comment by drgoku282** [comment]
Current 3.3 does not support 1.2 SM version.

Try using MichiS97 fork until I release a new preview version:
https://github.com/MichiS97/PKMN-NTR/releases

**Comment by drgoku282** [comment]
Duplicate of #80
