### ISSUE TITLE
Wonder trade bot switches to GTS and then crashes

### ISSUE THREAD

**Issue by Aqua-sama** [drgoku282/PKMN-NTR#85]
Hello, i have a problem using the Gen7 Wonder Trade Bot on my New Nintendo 3DS XL.
The Bot goes to GTS instead of the Wonder Trade platform.
Here i have my log:

Bot: START Gen 7 Wonder Trade bot
Bot: Backup boxes
NTR: Read 222720 bytes of data starting at address 0x330D9838
packet: cmd = 9, dataLen = 222720
Bot: Look for pokemon to trade
NTR: Read pokémon data at box 1, slot 1
packet: cmd = 9, dataLen = 232
NTR: Read sucessful - PID 0xE75FE521
Bot: Pokémon found - 0xE3A0
Bot: Set current box
NTR: Write value 0x00000000 at address 0x330D982F
NTR: Write sucessful
Bot: Press Trade Button
NTR: Touch the screen at 200,120
NTR: Touch screen command sent correctly
Bot: Test if the trademenu is shown
NTR: Read data at address 0x006749D4 during 5000 ms
NTR: Expected value 0xC2D00000 to 0xC2DFFFFF
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0x3F800000
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0x3F800000
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0x3F800000
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0x3F800000
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0x3F800000
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0x3F800000
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0x3F800000
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0x3F800000
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0x3F800000
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0x3F800000
NTR: Value in range: No
NTR: Command timed out
NTR: Read failed or outside of range
Bot: Press Trade Button
NTR: Touch the screen at 200,120
NTR: Touch screen command sent correctly
Bot: Test if the trademenu is shown
NTR: Read data at address 0x006749D4 during 5000 ms
NTR: Expected value 0xC2D00000 to 0xC2DFFFFF
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0x3F800000
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0x3F800000
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0x3F800000
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0x3F800000
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0x3F13E80B
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0x3F766E80
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0x3F586619
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0x3E2CA1D0
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0x3F800000
NTR: Value in range: No
packet: cmd = 9, dataLen = 4
NTR: Read sucessful - 0x3F6FEFF1
NTR: Value in range: No
NTR: Command timed out
NTR: Read failed or outside of range

**Comment by mmands994** [comment]
Have you tried disconnecting then reconnecting the bot again? I have had this same issue before, and doing that fixed it for me.

**Comment by drgoku282** [comment]
An update for the applciation should be up in a few hours, it maybe helps to solve this problem.

**Comment by MichiS97** [comment]
You should try using the latest beta version of my fork. The WT bot works fine for me using that version.

**Comment by drgoku282** [comment]
Checking previous issues, this seems a duplicate of #57.

**Comment by Aqua-sama** [comment]
fixed for me now
