### ISSUE TITLE
Forgot about some steps on comunicating with Luma 8.0 or newer

### ISSUE THREAD

**Issue by ThunderbInazuma** [drgoku282/PKMN-NTR#94]
Hi. 

I saw that on yout Wiki, you forgot to add these steps on "Luma 8.0 or newer". I know that they are inda obvious, but there are some "noob users" who might forgot about then:

Go to PSS / Festival Plaza (see the Generation 7 page for more options).
Connect to Internet.

Thanks for your work

**Comment by mmands994** [comment]
The wiki can be edited by anyone. No reason to make a pull request.

**Comment by ThunderbInazuma** [comment]
Oh, sorry. Didn't knew about that. Edited
