### ISSUE TITLE
Wondertrade bot literally dead after latest Luma.

### ISSUE THREAD

**Issue by mmands994** [drgoku282/PKMN-NTR#99]
It just doesn't work anymore. It's broken. It's dead.

Rest in pieces.

**Comment by Retrosol** [comment]
Wonder Trade Bot works fine hit me up on discord @Retrosol#3697 I will give you a hand.

**Comment by drgoku282** [comment]
Duplicate of #87 it seems. All discussion of latest Luma connection issues will be done there.
